/*
 * This file is generated by jOOQ.
 */
package com.lernapi.myapp.db.tables.pojos;


import java.io.Serializable;
import java.math.BigDecimal;
import java.math.BigInteger;


/**
 * Товары в категориях
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ProductsToCategories implements Serializable {

    private static final long serialVersionUID = 1345920087;

    private BigDecimal productsToCategoryId;
    private BigInteger categoryId;
    private BigInteger productId;

    public ProductsToCategories() {}

    public ProductsToCategories(ProductsToCategories value) {
        this.productsToCategoryId = value.productsToCategoryId;
        this.categoryId = value.categoryId;
        this.productId = value.productId;
    }

    public ProductsToCategories(
        BigDecimal productsToCategoryId,
        BigInteger categoryId,
        BigInteger productId
    ) {
        this.productsToCategoryId = productsToCategoryId;
        this.categoryId = categoryId;
        this.productId = productId;
    }

    public BigDecimal getProductsToCategoryId() {
        return this.productsToCategoryId;
    }

    public void setProductsToCategoryId(BigDecimal productsToCategoryId) {
        this.productsToCategoryId = productsToCategoryId;
    }

    public BigInteger getCategoryId() {
        return this.categoryId;
    }

    public void setCategoryId(BigInteger categoryId) {
        this.categoryId = categoryId;
    }

    public BigInteger getProductId() {
        return this.productId;
    }

    public void setProductId(BigInteger productId) {
        this.productId = productId;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ProductsToCategories (");

        sb.append(productsToCategoryId);
        sb.append(", ").append(categoryId);
        sb.append(", ").append(productId);

        sb.append(")");
        return sb.toString();
    }
}
