/*
 * This file is generated by jOOQ.
 */
package com.lernapi.myapp.db.tables.records;


import com.lernapi.myapp.db.tables.Products;

import java.math.BigDecimal;
import java.math.BigInteger;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * Товар
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ProductsRecord extends UpdatableRecordImpl<ProductsRecord> implements Record6<BigDecimal, String, String, String, BigInteger, BigDecimal> {

    private static final long serialVersionUID = -237990558;

    /**
     * Setter for <code>online_shop.products.products_id</code>.
     */
    public void setProductsId(BigDecimal value) {
        set(0, value);
    }

    /**
     * Getter for <code>online_shop.products.products_id</code>.
     */
    public BigDecimal getProductsId() {
        return (BigDecimal) get(0);
    }

    /**
     * Setter for <code>online_shop.products.name</code>. Наименование
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>online_shop.products.name</code>. Наименование
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>online_shop.products.description</code>. Описание
     */
    public void setDescription(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>online_shop.products.description</code>. Описание
     */
    public String getDescription() {
        return (String) get(2);
    }

    /**
     * Setter for <code>online_shop.products.model</code>. Модель
     */
    public void setModel(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>online_shop.products.model</code>. Модель
     */
    public String getModel() {
        return (String) get(3);
    }

    /**
     * Setter for <code>online_shop.products.amount</code>. Кол-во
     */
    public void setAmount(BigInteger value) {
        set(4, value);
    }

    /**
     * Getter for <code>online_shop.products.amount</code>. Кол-во
     */
    public BigInteger getAmount() {
        return (BigInteger) get(4);
    }

    /**
     * Setter for <code>online_shop.products.cost</code>. Стоимость
     */
    public void setCost(BigDecimal value) {
        set(5, value);
    }

    /**
     * Getter for <code>online_shop.products.cost</code>. Стоимость
     */
    public BigDecimal getCost() {
        return (BigDecimal) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<BigDecimal> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row6<BigDecimal, String, String, String, BigInteger, BigDecimal> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    @Override
    public Row6<BigDecimal, String, String, String, BigInteger, BigDecimal> valuesRow() {
        return (Row6) super.valuesRow();
    }

    @Override
    public Field<BigDecimal> field1() {
        return Products.PRODUCTS.PRODUCTS_ID;
    }

    @Override
    public Field<String> field2() {
        return Products.PRODUCTS.NAME;
    }

    @Override
    public Field<String> field3() {
        return Products.PRODUCTS.DESCRIPTION;
    }

    @Override
    public Field<String> field4() {
        return Products.PRODUCTS.MODEL;
    }

    @Override
    public Field<BigInteger> field5() {
        return Products.PRODUCTS.AMOUNT;
    }

    @Override
    public Field<BigDecimal> field6() {
        return Products.PRODUCTS.COST;
    }

    @Override
    public BigDecimal component1() {
        return getProductsId();
    }

    @Override
    public String component2() {
        return getName();
    }

    @Override
    public String component3() {
        return getDescription();
    }

    @Override
    public String component4() {
        return getModel();
    }

    @Override
    public BigInteger component5() {
        return getAmount();
    }

    @Override
    public BigDecimal component6() {
        return getCost();
    }

    @Override
    public BigDecimal value1() {
        return getProductsId();
    }

    @Override
    public String value2() {
        return getName();
    }

    @Override
    public String value3() {
        return getDescription();
    }

    @Override
    public String value4() {
        return getModel();
    }

    @Override
    public BigInteger value5() {
        return getAmount();
    }

    @Override
    public BigDecimal value6() {
        return getCost();
    }

    @Override
    public ProductsRecord value1(BigDecimal value) {
        setProductsId(value);
        return this;
    }

    @Override
    public ProductsRecord value2(String value) {
        setName(value);
        return this;
    }

    @Override
    public ProductsRecord value3(String value) {
        setDescription(value);
        return this;
    }

    @Override
    public ProductsRecord value4(String value) {
        setModel(value);
        return this;
    }

    @Override
    public ProductsRecord value5(BigInteger value) {
        setAmount(value);
        return this;
    }

    @Override
    public ProductsRecord value6(BigDecimal value) {
        setCost(value);
        return this;
    }

    @Override
    public ProductsRecord values(BigDecimal value1, String value2, String value3, String value4, BigInteger value5, BigDecimal value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ProductsRecord
     */
    public ProductsRecord() {
        super(Products.PRODUCTS);
    }

    /**
     * Create a detached, initialised ProductsRecord
     */
    public ProductsRecord(BigDecimal productsId, String name, String description, String model, BigInteger amount, BigDecimal cost) {
        super(Products.PRODUCTS);

        set(0, productsId);
        set(1, name);
        set(2, description);
        set(3, model);
        set(4, amount);
        set(5, cost);
    }
}
