/*
 * This file is generated by jOOQ.
 */
package com.lernapi.myapp.db.tables.records;


import com.lernapi.myapp.db.tables.ProductsToCategories;

import java.math.BigDecimal;
import java.math.BigInteger;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * Товары в категориях
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ProductsToCategoriesRecord extends UpdatableRecordImpl<ProductsToCategoriesRecord> implements Record3<BigDecimal, BigInteger, BigInteger> {

    private static final long serialVersionUID = 747035597;

    /**
     * Setter for <code>online_shop.products_to_categories.products_to_category_id</code>.
     */
    public void setProductsToCategoryId(BigDecimal value) {
        set(0, value);
    }

    /**
     * Getter for <code>online_shop.products_to_categories.products_to_category_id</code>.
     */
    public BigDecimal getProductsToCategoryId() {
        return (BigDecimal) get(0);
    }

    /**
     * Setter for <code>online_shop.products_to_categories.category_id</code>.
     */
    public void setCategoryId(BigInteger value) {
        set(1, value);
    }

    /**
     * Getter for <code>online_shop.products_to_categories.category_id</code>.
     */
    public BigInteger getCategoryId() {
        return (BigInteger) get(1);
    }

    /**
     * Setter for <code>online_shop.products_to_categories.product_id</code>.
     */
    public void setProductId(BigInteger value) {
        set(2, value);
    }

    /**
     * Getter for <code>online_shop.products_to_categories.product_id</code>.
     */
    public BigInteger getProductId() {
        return (BigInteger) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<BigDecimal> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row3<BigDecimal, BigInteger, BigInteger> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    public Row3<BigDecimal, BigInteger, BigInteger> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    public Field<BigDecimal> field1() {
        return ProductsToCategories.PRODUCTS_TO_CATEGORIES.PRODUCTS_TO_CATEGORY_ID;
    }

    @Override
    public Field<BigInteger> field2() {
        return ProductsToCategories.PRODUCTS_TO_CATEGORIES.CATEGORY_ID;
    }

    @Override
    public Field<BigInteger> field3() {
        return ProductsToCategories.PRODUCTS_TO_CATEGORIES.PRODUCT_ID;
    }

    @Override
    public BigDecimal component1() {
        return getProductsToCategoryId();
    }

    @Override
    public BigInteger component2() {
        return getCategoryId();
    }

    @Override
    public BigInteger component3() {
        return getProductId();
    }

    @Override
    public BigDecimal value1() {
        return getProductsToCategoryId();
    }

    @Override
    public BigInteger value2() {
        return getCategoryId();
    }

    @Override
    public BigInteger value3() {
        return getProductId();
    }

    @Override
    public ProductsToCategoriesRecord value1(BigDecimal value) {
        setProductsToCategoryId(value);
        return this;
    }

    @Override
    public ProductsToCategoriesRecord value2(BigInteger value) {
        setCategoryId(value);
        return this;
    }

    @Override
    public ProductsToCategoriesRecord value3(BigInteger value) {
        setProductId(value);
        return this;
    }

    @Override
    public ProductsToCategoriesRecord values(BigDecimal value1, BigInteger value2, BigInteger value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ProductsToCategoriesRecord
     */
    public ProductsToCategoriesRecord() {
        super(ProductsToCategories.PRODUCTS_TO_CATEGORIES);
    }

    /**
     * Create a detached, initialised ProductsToCategoriesRecord
     */
    public ProductsToCategoriesRecord(BigDecimal productsToCategoryId, BigInteger categoryId, BigInteger productId) {
        super(ProductsToCategories.PRODUCTS_TO_CATEGORIES);

        set(0, productsToCategoryId);
        set(1, categoryId);
        set(2, productId);
    }
}
