/*
 * This file is generated by jOOQ.
 */
package com.lernapi.myapp.db;


import com.lernapi.myapp.db.tables.Categories;
import com.lernapi.myapp.db.tables.Products;
import com.lernapi.myapp.db.tables.ProductsToCategories;
import com.lernapi.myapp.db.tables.records.CategoriesRecord;
import com.lernapi.myapp.db.tables.records.ProductsRecord;
import com.lernapi.myapp.db.tables.records.ProductsToCategoriesRecord;

import org.jooq.ForeignKey;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>online_shop</code> schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<CategoriesRecord> CATEGORIES_PK = UniqueKeys0.CATEGORIES_PK;
    public static final UniqueKey<ProductsRecord> PRODUCTS_PK = UniqueKeys0.PRODUCTS_PK;
    public static final UniqueKey<ProductsToCategoriesRecord> PRODUCTS_TO_CATEGORY_PK = UniqueKeys0.PRODUCTS_TO_CATEGORY_PK;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<ProductsToCategoriesRecord, CategoriesRecord> PRODUCTS_TO_CATEGORIES__FK_158205804874597 = ForeignKeys0.PRODUCTS_TO_CATEGORIES__FK_158205804874597;
    public static final ForeignKey<ProductsToCategoriesRecord, ProductsRecord> PRODUCTS_TO_CATEGORIES__FK_157868449927884 = ForeignKeys0.PRODUCTS_TO_CATEGORIES__FK_157868449927884;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class UniqueKeys0 {
        public static final UniqueKey<CategoriesRecord> CATEGORIES_PK = Internal.createUniqueKey(Categories.CATEGORIES, "categories_pk", new TableField[] { Categories.CATEGORIES.CATEGORIES_ID }, true);
        public static final UniqueKey<ProductsRecord> PRODUCTS_PK = Internal.createUniqueKey(Products.PRODUCTS, "products_pk", new TableField[] { Products.PRODUCTS.PRODUCTS_ID }, true);
        public static final UniqueKey<ProductsToCategoriesRecord> PRODUCTS_TO_CATEGORY_PK = Internal.createUniqueKey(ProductsToCategories.PRODUCTS_TO_CATEGORIES, "products_to_category_pk", new TableField[] { ProductsToCategories.PRODUCTS_TO_CATEGORIES.PRODUCTS_TO_CATEGORY_ID }, true);
    }

    private static class ForeignKeys0 {
        public static final ForeignKey<ProductsToCategoriesRecord, CategoriesRecord> PRODUCTS_TO_CATEGORIES__FK_158205804874597 = Internal.createForeignKey(Keys.CATEGORIES_PK, ProductsToCategories.PRODUCTS_TO_CATEGORIES, "fk_158205804874597", new TableField[] { ProductsToCategories.PRODUCTS_TO_CATEGORIES.CATEGORY_ID }, true);
        public static final ForeignKey<ProductsToCategoriesRecord, ProductsRecord> PRODUCTS_TO_CATEGORIES__FK_157868449927884 = Internal.createForeignKey(Keys.PRODUCTS_PK, ProductsToCategories.PRODUCTS_TO_CATEGORIES, "fk_157868449927884", new TableField[] { ProductsToCategories.PRODUCTS_TO_CATEGORIES.PRODUCT_ID }, true);
    }
}
