/*
 * This file is generated by jOOQ.
 */
package com.lernapi.myapp.db;


import com.lernapi.myapp.db.tables.Categories;
import com.lernapi.myapp.db.tables.Products;
import com.lernapi.myapp.db.tables.ProductsToCategories;


/**
 * Convenience access to all tables in online_shop
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>online_shop.categories</code>.
     */
    public static final Categories CATEGORIES = Categories.CATEGORIES;

    /**
     * Товар
     */
    public static final Products PRODUCTS = Products.PRODUCTS;

    /**
     * Товары в категориях
     */
    public static final ProductsToCategories PRODUCTS_TO_CATEGORIES = ProductsToCategories.PRODUCTS_TO_CATEGORIES;
}
